# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


version: 2
updates:
  # 更新项目级别的 Gradle 插件
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  # 更新应用模块的依赖
  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

    # 更新应用模块的依赖
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
